### ISSUE TITLE
IRSendRecv and any IR library work wrong 

### ISSUE THREAD

**Issue by Spawn2Death** [Seeed-Studio/Music_Shield#1]
IRSendRecv work wrong while play music (while read from SD card (readLen = cur_file.read(readBuf, READ_BUF_LEN);))

**Comment by KillingJacky** [comment]
Hi,
The two libraries uses the same timer, they can not co-exist at the same time.

**Comment by rwtoner** [comment]
Hello,

I am trying to get the "creatList" example to work. However, the serial monitor just keeps saying "Playlist is empty". I am using a Kingston 2GB Micro SD Card formatted as FAT16. I have 11 mp3 files in the root folder of the sd card. Can you provide any insight as to what is going on?
