### ISSUE TITLE
Error Types 

### ISSUE THREAD

**Issue by rickybobby15** [Seeed-Studio/Music_Shield#3]
I am getting error types in my arduino IDE.  The errors are pointing to the MusicPlayer.h file  

error: 'playingstatetype playingState', declared using anonymous type, is used but never defined [-fpermissive]
 extern playingstatetype playingState;

error: 'typedef volatile enum<anonymous> playingstatetype' does not refer to the unqualified type, so it is not used for linkage [-fpermissive]
 playingstatetype;

 error: 'ctrlState_t ctrlState', declared using anonymous type, is used but never defined [-fpermissive]
 extern ctrlState_t ctrlState;

error: 'typedef volatile enum<anonymous> ctrlState_t' does not refer to the unqualified type, so it is not used for linkage [-fpermissive]
 ctrlState_t;

do you know why this may be ?

**Comment by acicali** [comment]
@rickybobby15 - same here, any luck resolving this?

**Comment by Jepeto4** [comment]
Same for me. The interesting thing is we are already quite a few guys experiencing the same issue but there is response from Seedstudio. This may show their code is corrupted and the music shield is useless.

**Comment by lanselambor** [comment]
when using the newest Arduino IDE to compile the code errors above happened.
It's ok now, 
Just delete volatile before typedef enum
