### ISSUE TITLE
Playlist is empty

### ISSUE THREAD

**Issue by rwtoner** [Seeed-Studio/Music_Shield#4]
Hello,

I am trying to get the "creatList" example to work. However, the serial monitor just keeps saying "Playlist is empty". I am using a Kingston 2GB Micro SD Card formatted as FAT16. I have 11 mp3 files in the root folder of the sd card. Can you provide any insight as to what is going on?

Thanks

**Comment by lanselambor** [comment]
Hi rwtoner,

Check if SD card and slot are in good contact, try to use arduino IDE of arduino.cc for some libraries are different from IDE of arduino.org .

**Comment by lanselambor** [comment]
Hi rwtoner,

Any update?

**Comment by rwtoner** [comment]
Lambor,

The arduino IDE from arduino.cc http://arduino.cc/ and a 2GB Micro SD card type SDHC finally did the trick! Thanks for your help!!

Thanks,
Ryan Toner
