### ISSUE TITLE
Arduino freezes during setVolume call

### ISSUE THREAD

**Issue by woodcoder** [Seeed-Studio/Music_Shield#5]
Hi

I'm using this library with the LinkSprite Music Shield v1.2 (https://www.maplin.co.uk/p/music-shield-for-arduino-n99dg) and an Arduino Mega.  I'm using multiple calls to setVolume with a short delay between them (~40ms) to fade the volume of playing tracks up and down.

This works, but quite frequently the whole unit freezes up (sound stops and serial output stops).  I've narrowed this as happening during the call to `VS10XX::writeRegister` in the middle of the `SPI.transfer` calls.  If I place `Serial.print`s between each line the debug output looks like the call is getting interrupted and a second call is started?

Is there any way that some sort of interrupt could be being serviced that is calling the same method while it is mid-way through?  (Presumably sending a dodgy command to the shield and causing everything to crash/freeze?)

Any suggestions gratefully received!

Andy...

**Comment by KillingJacky** [comment]
As SD card used the hardware SPI bus, VS10xx chip uses a software SPI bus. Every SPI transfer consists of a lot of instruction calls, it can be easily interrupted by an ISR. In fact, the audio data is feed to VS10xx in an ISR, to get a stable sample rate. So any other VS10xx command calls are not encouraged to be call in the Arduino loop after the play has begun. The correct usage will be setup all the parameters (like volume) before the music gets played. 

For your use case, you need to adjust the volume in real time, so you should just put flags in the Arduino loops, and issue the VS10xx commands then in the ISR (real SPI transfer will happen). This will prevent the main loop and the ISR clash each other.

**Comment by woodcoder** [comment]
Ah that explains it -- thank you!

To do that, should I modify the MusicPlayer `ISR()` function in this library, or is there a way to hook this code in without modifying the library?

If I have to modify the library, would it make sense to always set the volume in this way (i.e. would you like to see a PR once I'm through)?

**Comment by KillingJacky** [comment]
Yes, this way will be a more robust way to adjust the volume, and surely we would like to merge your modification if you would like.

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
